src/main.ml

Gets streaming logs, build histories, and access control.

Update to latest OCurrent

---

Dockerfile
src/logging.ml
src/logging.mli
src/main.ml

Update logging configuration to match ocaml-ci. This adds metrics reporting and timestamps.

Update to latest OCurrent and improve logging

---

src/pipeline.ml

This is just to check that the Xen target still builds, allowing us to retire the Travis builds.

Build mirage-www for Xen (but don't deploy it)

---

src/pipeline.ml

Suggested by @hannesm.
See https://github.com/mirage/mirage/issues/1157

Work around race in mirage tool

---

.dockerignore
.gitmodules
Dockerfile
Makefile
README.md
deployer.opam
dune
dune-project
src/build.ml
src/dune
src/main.ml
src/pipeline.ml
src/pipeline.mli
src/s.ml

This builds all the Docker services using the new OCluster-managed cluster. It also builds OCluster itself. The OCluster worker image is a multi-arch image supporting 64-bit ARM and x86.

Build services using OCluster

---

dune
src/pipeline.ml

Merge this before deploying #56 or they will both try to deploy the same thing!

Move ocaml.org deployment to ci3 deployer

---

README.md

Document suggested workflows

---

.gitmodules
Dockerfile

Needed for #65.
This partly reverts commit 2051d98ea085f3c2b3054710de1e11128d439a15.

Vendor OCurrent again

---

README.md
src/build.ml
src/build.mli
src/dune
src/local.ml
src/pipeline.ml
src/pipeline.mli

Depends on https://github.com/ocurrent/ocurrent/pull/281.
/cc @tmcgilchrist, who volunteered to test this

Add ocurrent-deployer-local to make local testing easier

---

Dockerfile
config/docker/contexts/meta/09fea0dc07141bd3c02d4dd93686c641ffd9287a14a95fe6bf819bf67a141c23/meta.json
config/docker/contexts/meta/164166e560d44cd9b207f7e446ee4459eb869775585c95cbfa405dad66baf427/meta.json
config/docker/contexts/meta/222627c92f892a32347161b5bc34d88a0e70ce7a5da0bc07c096a9dd36edfbbe/meta.json
config/docker/contexts/meta/24a9362e41571d64bb261d1f176fc044301e55845d9244f271b78c4e4b486bac/meta.json
config/docker/contexts/meta/38f29d794d6f7ddc5309996ed09d54b07a0588d5a4d7c4138e6ce1b93ad04bbe/meta.json
config/docker/contexts/meta/411a15d6649316f33a7eb115c879d24dc3f6b5688e38fe38818cc053832b4f6b/meta.json
config/docker/contexts/meta/434fd5f6be88986a1e4a378bd665b6c9f7bc2c623fd377e225b19a4c8513a84e/meta.json
config/docker/contexts/meta/6ce6614459df6fa5fca1d002379a00754f206df6154dfcc325f2894af06bcb6f/meta.json
config/docker/contexts/meta/75863655a98cf38d6be04ce7c91c4443b2360db984183ffbf6b6a9bfd62e9572/meta.json
config/docker/contexts/meta/84677fcbf2aff0c2f74b1311b1683e0d93e35c2194b0f3a3b034316d2a268b12/meta.json
config/docker/contexts/meta/85e51a2d7cb3086f4caff38546519d492fa1c5ad2fee6bdf4c42687ad89edde6/meta.json
config/docker/contexts/meta/865b6b0c768086ed52d8dff71fca86a0635ab3001e025c985d2ebf0dfdcf8620/meta.json
config/docker/contexts/meta/8984accf3b8612c253dbddfe18cb5aed8aa59ca59b59c37b9e5f25ed6176e406/meta.json
config/docker/contexts/meta/afefb91b38561ce4c5ed9f03d31ba2e93d8d878f6d2817a2851641fbdd290343/meta.json
config/docker/contexts/meta/b44e0299c194837b0668195cde822e4ee2f6e33ac4cbfe9b33c7b80c1d829c46/meta.json
config/docker/contexts/meta/ba1150bbbac461d20356cdb3bc6b30c848d3b2428fcf6137fa34b348cd8333fa/meta.json
config/docker/contexts/meta/ba9e49ce0cf299df42d5541aaf98b68f550359b53c343f9f13df5772abfe59c7/meta.json
config/docker/contexts/meta/c30fe6fb128f811a20ff4162ed1ea61df017611f3ca001f4f2076268e86f5f92/meta.json
config/docker/contexts/meta/c51e4564f97259b68fd61b6f01ba95c993ae031c9ab97c0f4b70afaa553af033/meta.json
config/docker/contexts/meta/c9ef5df64aef21d39b9494b009bc5cbede32f0a9724527d27652e1cc7c4c2331/meta.json
src/pipeline.ml

Rename Docker contexts

---

config/docker/contexts/meta/a5f2cc8e484f013284b86ee6c4f4887264788e1a0cd78266ecd4469ee8072769/meta.json
src/pipeline.ml

Updated staging.ocaml.org

---

src/pipeline.ml

Deploys https://github.com/ocurrent/ocaml-ci/pull/499

Add deployer for gitlab.tezos.ci.dev branch.

---

src/pipeline.ml

it recently moved to a new host

update IP address of mirage host

---

config/docker/contexts/meta/56fe5c53b858bbb78cc4d56229528acead3e6be09990f60d5c708f2674cece3c/meta.json
src/pipeline.ml

Add new docs-ci staging environment:

Move docs-ci staging environment deploy.

---

src/pipeline.ml

Useful in testing local docker-compose stack running worker using Docker in Docker.
https://github.com/ocurrent/ocaml-docs-ci/pull/100

Add alpine linux variant of ocluster-worker

---

create-config.sh
src/pipeline.ml

Updated server names as per https://github.com/ocaml/infrastructure/issues/37

Renamed staging.docs.ci.ocaml.org

---

src/pipeline.ml

Useful for people running macOS on arm64

Add ARM64 builds of alpine

---

src/pipeline.ml

https://github.com/ocurrent/opam-repo-ci/issues/220

Opam-repo-ci (temporary) move to toxis

---

src/caddy.ml
src/pipeline.ml

Update deployer to address https://github.com/ocaml/infrastructure/issues/50

Make IP address optional

---

create-config.sh
src/pipeline.ml

See https://github.com/ocaml/infrastructure/issues/85

Update the (current) locations of ocaml.ci.dev and opam.ci.ocaml.org

---

create-config.sh
src/pipeline.ml

Possible way to address https://github.com/ocaml/infrastructure/issues/92

Publish opam.ocaml.org to a private registry

---

doc/services.md
src/pipeline.ml

Contributes to https://github.com/tarides/infrastructure/issues/388

Move opam-health-check to ocaml.org

---

doc/services.md
src/pipeline.ml

This adds a server instance. This is in support of
https://github.com/ocaml/infrastructure/issues/161
and of @mtelvers' work to improve the capacity of ocaml.org

Update config for ocaml.org instances

---

src/pipeline.ml

Effectively cherry-picked from https://github.com/ocurrent/ocurrent-deployer/pull/166

Enable Buildkit on OCaml-CI

---

doc/services.md
src/pipeline.ml

Enable Buildkit on OCaml-CI Gitlab and www

---

.gitmodules
Dockerfile
deployer.opam
dune-project

Closes https://github.com/tarides/infrastructure/issues/389

Replace git submodules with published dependencies

---

src/pipeline.ml

Enable BuildKit on docker-base-images
