ocurrent/ocurrent-deployer

Dockerfile, src/build.ml, src/build.mli, src/main.ml, src/pipeline.ml, src/pipeline.mli
This allows us to check that each PR is still deployable.
Note: this also disables the use of BuildKit, which is not safe now that we are testing PRs too (because it allows poisoning of the download cache).
=> Build all branches, not just the live deployments

deployer.opam, src/dune, src/mirage.ml, src/mirage.mli, src/pipeline.ml
Build unikernels on the deployment host and then rsync to the target. This is to support targets that don't run Docker.
=> Build unikernels locally

src/pipeline.ml
Now that the deployment seems to be working, it's probably easiest to deploy from the master branch.
/cc @hannesm
=> Deploy mirage-www from master branch

src/build.ml, src/build.mli, src/pipeline.ml, src/s.ml
Instead of trying to make the build code work with both Docker services and unikernels, provide a functor that can be used with whatever types you like.
=> Refactor deployer

src/pipeline.ml
Otherwise, if we later deploy a new (bad) version and need to roll back quickly, we may find the old version isn't around any longer.
=> Tag deployed unikernels to prevent them getting GC'd

src/pipeline.ml
This reverts commit 7e76e043f9f52a09b09983279a957899f297907c. It's not needed since https://github.com/mirage/mirage-www/pull/680.
=> Revert "Work around race in mirage tool"

src/build.ml, src/main.ml, src/pipeline.ml, src/s.ml
Instead of passing the result of the build step to the deploy, give the source and build info to the deploy function directly. It can just call the build step itself if it wants to, but it can also behave differently.
This will be useful with the new build scheduler, because we need to know whether we're deploying to decide whether to save the resulting image.
=> Make deployment system more flexible

src/pipeline.ml
Often you only want to update one and updating the others is disruptive.
=> Use separate branches for deploying the scheduler and the workers

deployer.opam, dune-project, src/pipeline.ml
This PR should hopefully fix https://github.com/ocaml/ocaml.org/issues/1247 (related work on https://github.com/ocaml/ocaml.org/pull/1253) in which the `git log` command for getting the contributors of the ocaml.org site failed in production/staging but not locally. 
This is likely caused by using the default `Docker.Spec` build context which excludes `.git`. Here it has been enabled for the ocaml.org production and staging deployments.
The `.git` directory shouldn't make it to the server as we copy over the build from another build stage in the Dockerfile https://github.com/ocaml/ocaml.org/blob/master/Dockerfile.deploy#L13
=> configure ocaml.org to include git

Dockerfile
The previous version has a memory leak and gets slower over time.
=> Update Dockerfile to get fixed mirage-crypto (on ci3)

Dockerfile
The previous version has a memory leak and gets slower over time.
=> Update Dockerfile to get fixed mirage-crypto

src/pipeline.ml
on the packet.net machine, I adapted /usr/local/bin/mirage-redeploy to know about a "next" unikernel (passed as $1). In DNS (mirageos-zone repository) I added next.mirage.io and next.mirageos.org entries.
//cc @talex5 @TheLortex
=> add next mirage unikernel website

src/pipeline.ml
This is no longer the main deployer.
=> Deploy toxis from live-toxis branch

src/pipeline.ml
This image will be added in https://github.com/ocurrent/ocaml-docs-ci/pull/35
As documentation is stored in a git repository, there's not straightforward access to the data (except by `git` cloning and merging).
We use an http server based on ocaml-git to expose the files and explore the output.
=> Docs-ci: add git-http-website deployment

src/main.ml, src/pipeline.ml, src/pipeline.mli
This service is now only for deploying unikernels, and no longer deploys itself.
=> Deploy this service from ci3 in future

src/pipeline.ml
This means that the old deployer no longer needs to deploy itself, avoiding the confusion of having two deployers on a single repository.
=> Deploy unikernel pipeline from ci3

src/pipeline.ml
Because of the new v3.ocaml.org deployment, the build of `Dockerfile.web` deployed as `docs-ci-web` is not relevant anymore.
=> ocaml-docs-ci: remove the deployment of docs-ci-web

Dockerfile, README.md, src/build.ml, src/local.ml, src/main.ml
Includes with Checks API setting more details and support for rebuilding jobs.
Brings in the requirement to set `--github-webhook-secret-file` to validate web hooks.
=> Update ocurrent to latest version.

src/pipeline.ml
I think this change was on live-ci3 but not on master.
Furthermore, the 2 services that this is deploying aren't matching the names in the OCaml.
`current-bench_frontend` and `current-bench_pipeline`
=> Match packet_current_bench to docker context name.

src/pipeline.ml
Added an s390x build of `ocluster-worker` to the `ocurrent-deployer` pipeline so the worker can be updated.
=> Add s390x worker to deployer pipeline

src/pipeline.ml
The large image pushes to docker are sometimes timing out.
=> Increase timeout for opam2web.

deployer.opam, dune-project, src/build.ml, src/dune, src/index.ml, src/index.mli, src/local.ml, src/main.ml, src/pipeline.ml, src/s.ml, test/dune, test/test.ml, test/test_index.ml
This requires supporting persistence
in SQLite so that we can lookup job-ids
that correspond to a commit.
Dependent on https://github.com/ocurrent/ocurrent/pull/364 and updating ocurrent to point to latest master once this is merged.
=> Wiring in check-run and check-suite support.

src/local.ml, src/main.ml
Pulls in https://github.com/ocurrent/ocurrent/pull/366
> Rationale: After deploying the check_run/suite work, we found that even though GitHub will only show a re-run button if you have write permissions to a repository, there is an additional check in the code on our end that ignores webhook requests unless they are from a member of a hard-coded list. This PR removes that restriction.
=> Removes role check for GitHub webhooks.

Dockerfile, config/docker/contexts/meta/2b2d409edce7cf1d000adf0d93ec45c8affa00363cc0cee5b647e860ef2d49ec/meta.json, src/aws.ml, src/dune, src/pipeline.ml
There are currently four pipelines: [www.ocaml.org](www.ocaml.org) live and staging and [opam-3.ocaml.org](opam-3.ocaml.org) live and staging.  The Docker containers for these services run on individually managed Amazon EC2 instances.
This PR adds pipelines, intended to replace the current deployments, with Amazon Fargate tasks deployed through Amazon Elastic Container Service (ECS).
ECS allows Docker containers to be deployed directly to either EC2 instances or to Amazon Fargate.  Fargate is a managed compute resource designed to run Docker containers.
A `docker-compose.yaml` is created using `Aws.compose` which describes the service including details of memory, CPU and storage.  This is deployed using `docker --context awsecs compose up`.  The Docker Compose CLI converts the …
=> Added AWS ECS pipelines

src/pipeline.ml
@shakthimaan confirms that this service is no longer needed.
=> Removed ocurrent/current-bench from ocurrent-deployer

src/pipeline.ml
[OCaml-multicore-CI](https://github.com/ocurrent/ocaml-multicore-ci) and [OCaml-CI](https://github.com/ocurrent/ocaml-ci) will move to use [solver-service](https://github.com/ocurrent/solver-service).
=> Add deployer for ocurrent/solver-service

src/pipeline.ml
We're adding monitoring to mirage.io, it's introducing additional configure-time flags: https://github.com/mirage/mirage-www/pull/767
=> Add monitoring flags for mirage.io website

src/pipeline.ml
The solver service will now be deployed natively rather than through a Docker container matching the deployment of an ocluster worker.
=> Remove solver service container deployment on ci4

src/main.ml
For coverage over the upcoming holidays. Can be reverted in mid January 2023.
=> Add me to the admin list

src/pipeline.ml
Allows for tracking ocaml/opam correctly.
=> Add ocaml/opam as a parameter for opam2web builds

deployer.opam, dune-project, src/build.ml, src/index.ml, src/mirage.ml, src/pipeline.ml, src/s.ml
Before 
After
The main change is 07406b636cc66a56f5aede447e86f02bde8aa0dd and should be sufficient.
The second change d6982c88dfb57a2f5132b89b6c07a62c76651011 is an attempt to get rid of the 2 build boxes that are actually a single build.
=> Display build steps as clickable boxes

src/pipeline.ml
Adds clarke to the images to be built and pushed to docker. The power monitors will probably be installed and updated like ocluster-worker services rather than from the deployer.
=> Build clarke images

Dockerfile
From Docker Engine version 23.0.0, Buildx is distributed in a separate package: `docker-buildx-plugin`. In earlier versions, Buildx was included in the `docker-ce-cli`.
=> Added docker-buildx-plugin

src/pipeline.ml
This PR supports `docker login` in `docker pull`.  The goal is to overcome the rate limit by using an authenticated user.
Fixes #172
=> Use docker login on pull

src/pipeline.ml
[ocurrent/multicoretests-ci](https://github.com/ocurrent/multicoretests-ci) is a CI for [ocaml-multicore/multicoretests](https://github.com/ocaml-multicore/multicoretests).
=> Add multicoretests-ci

create-config.sh, src/pipeline.ml
Enable ARM64 builds for OCaml-CI and Opam-Repo-CI ref https://github.com/ocaml/infrastructure/issues/51.
=> Enable ARM64 builds for OCaml-CI and Opam-Repo-CI

src/pipeline.ml
Specifically for deployability and builds on ocluster-worker project but it might also help on ARM64 / RiscV builds on the same project.
=> Set ulimit for POWER64 backend.

src/pipeline.ml
`peertube-bullseye` has been replaced by `peertube-bookworm`.
=> Bookworm replaces Bullseye

src/local.ml, src/main.ml, src/pipeline.ml, src/pipeline.mli
Currently the list of services is fed directly into a single `Current.unit` pipeline, this PR separates them out so that we can generate documentation from the list of services.
Future PRs for documentation and testing will depend on this PR. It is broken up to keep reviews manageable.
=> Separate services from pipeline

README.md, doc/doc.ml, doc/dune, doc/services.md, src/aws.ml, src/build.ml, src/build.mli, src/cluster.ml, src/docker_registry.ml, src/packet_unikernel.ml, src/pipeline.ml, src/pipeline.mli
Run `dune build @doc` to generate a markdown file documenting the list of services, which can be `dune promote`ed if it differs from the existing one. This also serves as an expect test.
The section at the bottom is an excerpt from the new `services.md`. We include the dockerfiles that are deployed, and for which branches and docker tags. We don't include the specific targets — e.g. `` `Ci3 ``, `` `Opamrepo ``, etc. — but this can be included if it would be useful.
A particular note is that the code in `pipeline.ml` includes services for which there are no deployments, such as `clarke`, likely just as a way to keep track of them. These services are not included in `services.md`.
---
...
- `Dockerfile` on arches: x86_64, arm64
- branch `live` at `ocurrent/opam-repo-ci:live`
- …
=> Generate list of services as documentation

Dockerfile
The Docker Compose CLI project has been retired.  See https://github.com/docker-archive/compose-cli.
This plugin was needed to provide support for pushing to Amazon ECS.  However, we do not currently deploy to ECS so this can be dropped and revisited if we ever decide to use ECS.
=> Remove explicit installation of Docker Compose CLI

.gitignore, deployer.opam, deployer.opam.template, dune-project
- Configure the package so we can (hopefully) finally actually address https://github.com/ocurrent/ocaml-ci/issues/931 for our dev repos (if this works, I'll update the issue to record it and make the change on all our other repos)
- Adds a fix for missing dep constraint
:warning: Auto-merge enabled, so please only approve PR if it is good to merge!
=> Get the CI green

Dockerfile, create-config.sh, doc/services.md, src/cluster.ml, src/pipeline.ml
v2.ocaml.org is now a redirect to ocaml.org.
=> Remove v2.ocaml.org

doc/doc.ml, src/access.ml, src/access.mli, src/dune, src/local.ml, src/main.ml, src/pipeline.ml, src/pipeline.mli, test/test_index.ml
This is a prelude to https://github.com/tarides/infrastructure/issues/388 and to the (possible) future step of separating out the specific deployer configurations from the general purpose deployer library.
The commits explain the motivation for each changeset (which should be logically complete), tho there is some slight wandering evolution in the sequence of commits. The main outcomes are:
- The access control logic is moved to a single (tested) function.
- The "flavours" are re-conceived (internally) as "Deployers", satisfying a single (minimal) interface. 
- All logic and data that is specific to a particular deployer is moved into the respective module implementing the deployer. This allows us to reason about the entirety of a deployer's configuration locally, from within the …
=> Refactor the API of the modules that define the "flavours" of deployer pipelines

doc/services.md, src/pipeline.ml
Closes https://github.com/tarides/infrastructure/issues/388
With this change, I think we now have all of the indicated services grouped
correctly (i.e. all "Ecosystem services" under the ocaml.org deployer), with the
exception of https://github.com/ocurrent/current-bench. The latter has been
indicated as belonging in this group, but it is not currently handled by the
deployer.
=> Move opam-repo-ci to ocaml.org

README.md, create-config.sh, doc/services.md, src/cluster.ml, src/pipeline.ml
Please check and test carefully, since I don't have a clue on how such a rename should be done, and whether any other steps are necessary. Thanks a lot.
Reference: https://github.com/mirage/mirage-www/pull/845
Note: the DNS entries for ci.mirageos.org and deploy.mirageos.org are already established.
=> mirage.io moves to mirageos.org

doc/doc.ml, doc/services.md, src/cluster.ml, src/pipeline.ml, src/pipeline.mli
The current code declares a type like
```ocaml
type service =
[ `Ci of string
; ...
; `Ocamlorg_v3c of string 
]
```
Values of this type are used to mark a field in the deployed services 
in `pipeline.ml`. Values of this type are not used anywhere in the 
project except for `cluster.ml`. In that location, they are used to map
to different applications of `pull_and_serve`. Once we remove the unused
AWS entry, every application of `pull_and_serve` is uniform *except* 
that different modules are packed into arguments. The only difference
between these modules is a string value provided when applying the
`Current_docker.Make` to contruct instances of `Current_docker.S.DOCKER`. And
the string value provided there exposes information that we should only know if
you are within the context of a …
=> Refactor to remove abstraction leak into `cluster.ml`

doc/services.md, src/pipeline.ml
This PR changes the service `uri` to match reality and add a new service on `ocaml-dune/binary-distribution:staging`. This service is in charge of building the preview.dune.build website in a context of a test environment.
=> feat: add staging branch forocaml-dune/binary-distribution

src/pipeline.ml
This PR adds me as an admin, so I can re-run the build for dune binary distribution when it is broken without having to ask the other admins to re-run the pipeline.
=> chore: add maiste as OCaml_org admin

Dockerfile
=> Switch the Dockerfile to BuildKit features
